<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MailClient.Exchange</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MailClient.Core\MailClient.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MailClient.Tests" />
  </ItemGroup>
</Project>
